"""empty message

Revision ID: 95c63ed67d94
Revises: 3beffd614604
Create Date: 2019-10-02 13:43:40.536639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c63ed67d94'
down_revision = '3beffd614604'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('piece')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('piece',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('piece_url', sa.VARCHAR(length=64), nullable=True),
    sa.Column('image_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
